const Path = {
    LOGIN : 'user/auth/login',
    SIGNUP : 'user/auth/signup',
    RESEND_OTP : 'user/auth/resend_otp',
    SIGNUP_VALIDATE : 'user/auth/signup_validate',
    FORGOT_PASSWORD : 'user/auth/forgot_password',
    GET_GAME_TYPE_LIST : 'props/lobby/get_game_type_list',
    GET_DAILY_STREAK_COINS : 'user/coins/get_daily_streak_coins',
    CLAIM_COINS : 'user/coins/claim_coins',
    GET_UNREAD_NOTIFICATION : 'user/notification/get_unread_notification',
    GET_LOBBY_FILTER : 'props/lobby/get_lobby_filter',
    GET_LOBBY_FIXTURE : 'props/lobby/get_lobby_fixture',
    GET_FIXTURE_DETAILS : 'props/lobby/get_fixture_details',
    GET_CONTEST_DETAIL : 'props/contest/get_contest_detail',
    GET_CONTEST_USERS : 'props/contest/get_contest_users',
    GET_LINEUP_MASTER_DATA : 'props/lineup/get_lineup_master_data',
    GET_ALL_ROSTER : 'props/lineup/get_all_roster',
    CHECK_FANTASY_POINTS : 'props/lineup/check_fantasy_points',
    GET_USER_BALANCE : 'user/finance/get_user_balance',
    JOIN_GAME : 'props/contest/join_game',
    CREATE_ROUND_TEAM : 'props/lineup/create_round_team',
    GET_USER_CONTEST_BY_STATUS : 'props/contest/get_user_contest_by_status',
    GET_MY_TEAM_DATA : 'props/contest/get_my_team_data',
    GET_USER_LINEUP : 'props/lineup/get_user_lineup',
    UPDATE_TEAM_LINEUP : 'props/lineup/update_team_lineup',
    GET_CONTEST_LEADERBOARD : 'props/contest/get_contest_leaderboard',
    GET_H2H_LEADERBOARD : 'props/contest/get_h2h_leaderboard',
    CREATE_USER_CONTEST: 'props/private_contest/create_user_contest',
    GET_USERNAME_LIST: 'props/private_contest/get_username_list',
    INVITE_CODE: 'props/contest/get_contest_invite_code',
    GET_BRACKET_CONTEST_LEADERBOARD : 'props/contest/get_bracket_contest_leaderboard',
    GET_BRACKET_TEAM_COMPARE: 'props/contest/get_bracket_team_compare',
    COLLECTION_LIST: 'props/private_contest/get_collection_list',
    CREATE_CONTEST_MASTER_DATA: 'props/private_contest/create_contest_master_data',
    SENT_CONTEST_INVITE: 'props/private_contest/sent_contest_invite',
    CHECK_ELIGIBILITY_FOR_CONTEST: 'props/contest/check_eligibility_for_contest',
    GET_MY_STATS: 'props/lobby/get_my_stats',
    GET_MY_STATS_DETAIL: 'props/lobby/get_my_stats_detail',
    
}
export default Path
