const Images = {
    noInternet: require('../../assets/no_network.png'),
    blurTopRight: require('../../assets/Images/blurTopRight.png'),
    blurTopLeft: require('../../assets/Images/blurTopLeft.png'),
    bottomLeft: require('../../assets/Images/bottomLeft.png'),
    LOGO: require('../../assets/Images/logo.png'),
    PATHBG: require('../../assets/Images/pathBG.png'),
    MAIL: require('../../assets/Images/mail.png'),
    PASSWORD: require('../../assets/Images/Password.png'),
    IC_SOCIAL: require('../../assets/Images/ic_social.png'),
    RIGHT_VERTICAL: require('../../assets/Images/right_vertical.png'),
    LEFT_VERTICAL: require('../../assets/Images/left_vertical.png'),
    LOCK: require('../../assets/Images/lock.png'),
    VIEW_ARROW: require('../../assets/Images/view_arrow.png'),
    ARROW: require('../../assets/Images/arrow.png'),
    USER: require('../../assets/Images/user.png'),
    REFERRAL: require('../../assets/Images/Referral.png'),
    TIMER: require('../../assets/Images/Timer.png'),
    EDIT: require('../../assets/Images/edit.png'),
    POLYGON: require('../../assets/Images/Polygon.png'),
    POLYGON_INACTIVE: require('../../assets/Images/Polygon_inactive.png'),
    ACTIVEPOLYGON: require('../../assets/Images/activePolygon.png'),
    ACTIVELEADERBOARD: require('../../assets/Images/activeLB.png'),
    INACTIVELEADERBOARD: require('../../assets/Images/inactiveLB.png'),
    BRODCAST: require('../../assets/Images/brodcast.png'),
    IC_CALENDER: require('../../assets/Images/ic_calender.png'),
    CALENDAR: require('../../assets/Images/calendar.png'),
    SMS: require('../../assets/Images/sms.png'),
    MOONIC: require('../../assets/Images/moonIC.png'),
    IC_ClOSE: require('../../assets/Images/close-circle.png'),
    IC_INFO: require('../../assets/Images/info-circle.png'),
    HTP1: require('../../assets/Images/htp1.png'),
    HTP2: require('../../assets/Images/htp2.png'),
    HTP3: require('../../assets/Images/htp3.png'),
    HTP4: require('../../assets/Images/htp4.png'),
    CUP: require('../../assets/Images/cup.png'),
    CUPSTAR: require('../../assets/Images/cupstar.png'),
    RANKING: require('../../assets/Images/ranking.png'),
    DOCUMENT_TEXT: require('../../assets/Images/document-text.png'),
    IC_SPORTS_HUB: require('../../assets/Images/ic_sports_hub.png'),
    ROW_VERTICAL: require('../../assets/Images/row-vertical.png'),
    LIGHTCRCL: require('../../assets/Images/lightCrcl.png'),
    IC_COIN: require('../../assets/Images/ic_coin.png'),
    IC_CORRECT: require('../../assets/Images/ic_correct.png'),
    QUESTION: require('../../assets/Images/question.png'),
    IC_FILTER: require('../../assets/Images/Filterbutton.png'),
    IC_TROPHY: require('../../assets/Images/trophy.png'),
    FILLTROPHY: require('../../assets/Images/filltrophy.png'),
    IC_SHARE: require('../../assets/Images/share.png'),
    LEFTVIEW: require('../../assets/Images/leftView.png'),
    IC_NOTIFICATION: require('../../assets/Images/notification-bing.png'),
    IC_EYE: require('../../assets/Images/eye.png'),
    BURGER: require('../../assets/Images/burger.png'),
    RESET: require('../../assets/Images/reset.png'),
    VS: require('../../assets/Images/vs.png'),
    BOOK:require('../../assets/Images/book.png'),
    CALCULATOR:require('../../assets/Images/calculator.png'),
    DOLLAR:require('../../assets/Images/dollarcircle.png'),
    DROPDOWN:require('../../assets/Images/dropdown.png'),
    INFOCIRCLE:require('../../assets/Images/info-circle.png'),
    NOTE:require('../../assets/Images/note.png'),
    SOCIAL_IMAGES:require('../../assets/Images/social_images.png'),
    CROSS:require('../../assets/Images/cross.png'),
    CIRCLE:require('../../assets/Images/checkbox.png'),
    COPY:require('../../assets/Images/copy.png'),
    JOIN:require('../../assets/Images/join.png'),
    RECTANGLE: require('../../assets/Images/Rectangle.png'),
    RECTANGLE79: require('../../assets/Images/Rectangle79.png'),
    LEADERBOARD_RECTANGLE: require('../../assets/Images/Rectangle66.png'),
    SPARK: require('../../assets/Images/spark.png'),
    SEARCH: require('../../assets/Images/search.png'),
    ARROW_DOWN: require('../../assets/Images/arrow-down.png'),
    ACTIVEBG: require('../../assets/Images/activeBg.png'),
    INACTIVEBG: require('../../assets/Images/inactiveBg.png'),
    IC_ARROW: require('../../assets/Images/ic_arrow.png'),
    VECTOR: require('../../assets/Images/Vector.png'),
    EDITIC: require('../../assets/Images/editIC.png'),
    PNPHEADER: require('../../assets/Images/pnpHeader.png'),
    EMPTYIMG: require('../../assets/Images/emptyImg.png'),
    ADDEMPTY: require('../../assets/Images/addEmpty.png'),
    VIEW_FPTS: require('../../assets/Images/view_fpts.png'),
    IC_SMALL_COIN: require('../../assets/Images/ic_small_coin.png'),
    IC_BONUS: require('../../assets/Images/ic_bonus.png'),
    X: require('../../assets/Images/X.png'),
    USER_NAME: require('../../assets/Images/user_name.png'),
    POPUPLOGO: require('../../assets/Images/popupLogo.png'),
    ARROW_CIRCLE_DOWN: require('../../assets/Images/arrow-circle-down.png'),
    CONTEST_BOX_SHADOW: require('../../assets/Images/contest_box_shadow.png'),
    DOT: require('../../assets/Images/dot.png'),
    ARROW4: require('../../assets/Images/arrow4.png'),
    EYE_BG: require('../../assets/Images/eye_bg.png'),
    RANKING_ACTIVE: require('../../assets/Images/ranking_active.png'),
    MYTEAMBG: require('../../assets/Images/myteamBg.png'),
    NBA: require('../../assets/Images/NBA.png'),
    NFL: require('../../assets/Images/NFL.png'),
    VIEW_RIGHT: require('../../assets/Images/viewRight.png'),
    
}
export default Images;
